[package]
name                = "ellie"
version             = "0.7.0-alpha"
authors             = ["Kamran Mackey <kamranm1200@gmail.com>"]
description         = "A Discord bot written in Rust with Serenity."
homepage            = "https://github.com/KamranMackey/Ellie"
repository          = "https://github.com/KamranMackey/Ellie.git"
keywords            = ["discord", "bot", "serenity"]
edition             = "2018"
license             = "MIT"
readme              = "README.md"
include             = ["src/**/*", "config.sample.toml", "build.rs", "Cargo.toml", "README.md"]

[dependencies]
byte-unit           = "3.0.3"
chrono              = "0.4.11"
git2                = "0.13.5"
graphql_client      = "0.9.0"
humantime           = "2.0.0"
isolang             = "1.0.0"
itertools           = "0.9.0"
kuchiki             = "0.8.0"
lastfm-rs           = "0.2.2"
reqwest             = "0.10.4"
percent-encoding    = "2.1.0"
rspotify            = { git = "https://github.com/KamranMackey/rspotify" }
serenity            = { git = "https://github.com/KamranMackey/serenity.git", branch = "kamrans-fork-await" }
serde               = { version = "1.0.110", features = ["derive"] }
serde_json          = "1.0.53"
tokio               = { version = "0.2.21", features = ["macros"] }
toml                = "0.5.6"
tracing             = "0.1.14"
tracing-log         = "0.1.1"
tracing-subscriber  = "0.2.5"
sqlx                = "0.3.5"
sysinfo             = "0.14.2"
