[package]
name = "ellie"
version = "0.3.3"
authors = ["Kamran Mackey <kamranm1200@gmail.com>"]
publish = false
build = "build.rs"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
built = { git = "https://github.com/KamranMackey/built" }

[dependencies]
built = { git = "https://github.com/KamranMackey/built" }
chrono = "0.4"
dotenv = "0.15"
git2 = "0.11"
humantime = "2.0"
itertools = "0.8"
lastfm-rs = { git = "https://github.com/KamranMackey/lastfm-rs" }
log = "0.4"
pretty_env_logger = "0.3"
reqwest = "0.10"
rusqlite = { git = "https://github.com/KamranMackey/rusqlite", features = ["bundled"] }
rspotify = { git = "https://github.com/KamranMackey/rspotify" }
serenity = { git = "https://github.com/serenity-rs/serenity.git", branch = "current" }
serde = "1.0"
serde_json = "1.0"
