[package]
name = "ellie"
version = "0.0.1"
authors = ["Kamran Mackey <kamranm1200@gmail.com>"]
edition = "2018"

build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
humantime = "1.3.0"
serenity = { git = "https://github.com/serenity-rs/serenity.git", branch = "current" }
dotenv = "0.15"
reqwest = "0.9"
chrono = "0.4"
itertools = "0.8"
serde = "1.0"
serde_json = "1.0"
log = "0.4"
pretty_env_logger = "0.3"
rspotify = { git = "https://github.com/KamranMackey/rspotify" }
lastfm-rs = { git = "https://github.com/KamranMackey/lastfm-rs" }
git-testament = "0.1"
lazy_static = "1"

