[package]
name                = "ellie"
version             = "0.7.0-alpha"
authors             = ["Kamran Mackey <kamranm1200@gmail.com>"]
description         = "A Discord bot written in Rust with Serenity."
homepage            = "https://github.com/KamranMackey/Ellie"
repository          = "https://github.com/KamranMackey/Ellie.git"
keywords            = ["discord", "bot", "serenity"]
edition             = "2018"
license             = "MIT"
readme              = "README.md"
include             = ["src/**/*", "config.sample.toml", "Cargo.toml", "README.md"]

[dependencies]
anyhow              = "1.0.40"
aspotify            = "0.7.0"
byte-unit           = "4.0.10"
chrono              = "0.4.19"
git2                = "0.13.17"
humantime           = "2.1.0"
itertools           = "0.10.0"
lastfm-rs           = "0.5.0"
serde               = { version = "1.0.125", features = ["derive"] }
serde_json          = "1.0.64"
tokio               = { version = "1.4.0", features = ["full"] }
toml                = "0.5.8"
tracing             = "0.1.25"
tracing-futures     = "0.2.5"
tracing-log         = "0.1.2"
tracing-subscriber  = "0.2.17"

[dependencies.reqwest]
version = "0.11.2"
default-features = false
features = ["json", "multipart", "stream", "rustls-tls"]

[dependencies.serenity]
git                 = "https://github.com/serenity-rs/serenity"
branch              = "current"
default-features    = true
features            = ["collector", "unstable_discord_api", "rustls_backend"]

[dependencies.sqlx]
git                 = "https://github.com/launchbadge/sqlx"
default-features    = false
features            = ["runtime-tokio-rustls", "macros", "postgres", "uuid"]
