[package]
name = "ellie"
version = "0.1.0"
authors = ["Kamran Mackey <kamranm1200@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serenity = { git = "https://github.com/serenity-rs/serenity.git", branch = "current" }
dotenv = "0.15"
reqwest = "0.9"
chrono = "0.4"
serde = "1.0"
serde_json = "1.0"
# rspotify = "0.7"
lastfm-rs = { git = "https://github.com/KamranMackey/lastfm-rs" }
