[package]
name                = "ellie"
version             = "0.6.0-alpha"
authors             = ["Kamran Mackey <kamranm1200@gmail.com>"]
description         = "A Discord bot written in Rust with Serenity."
homepage            = "https://github.com/KamranMackey/Ellie"
repository          = "https://github.com/KamranMackey/Ellie.git"
keywords            = ["discord", "bot", "serenity"]
edition             = "2018"
license             = "MIT"
readme              = "README.md"
include             = ["src/**/*", "config.sample.toml", "build.rs", "Cargo.toml", "README.md"]

[dependencies]
byte-unit           = "3.0.3"
chrono              = "0.4.11"
git2                = "0.13.1"
graphql_client      = "0.9.0"
humantime           = "2.0.0"
isolang             = "1.0.0"
itertools           = "0.9.0"
kuchiki             = "0.8.0"
lastfm-rs           = "0.2.2"
lazy_static         = "1.4.0"
log                 = "0.4.8"
pretty_env_logger   = "0.4.0"
reqwest             = "0.10.4"
percent-encoding    = "2.1.0"
rusqlite            = { git = "https://github.com/jgallagher/rusqlite", features = ["bundled"] }
rspotify            = { git = "https://github.com/KamranMackey/rspotify", features = ["blocking"] }
serenity            = { git = "https://github.com/KamranMackey/serenity.git", branch = "kamrans-fork" }
serde               = { version = "1.0.106", features = ["derive"] }
serde_json          = "1.0.51"
toml                = "0.5.6"
sysinfo             = "0.12.0"
