[package]
name = "ellie"
version = "0.1.2"
authors = ["Kamran Mackey <kamranm1200@gmail.com>"]
edition = "2018"

build = "build.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4"
dotenv = "0.15"
git-testament = "0.1"
humantime = "1.3.0"
itertools = "0.8"
lastfm-rs = { git = "https://github.com/KamranMackey/lastfm-rs" }
lazy_static = "1"
log = "0.4"
pretty_env_logger = "0.3"
reqwest = "0.10"
rspotify = { git = "https://github.com/KamranMackey/rspotify" }
serenity = { git = "https://github.com/serenity-rs/serenity.git", branch = "current" }
serde = "1.0"
serde_json = "1.0"
