[package]
name = "ellie"
version = "0.4.2"
authors = ["Kamran Mackey <kamranm1200@gmail.com>"]
description = "A Discord bot written in Rust with Serenity."
homepage = "https://github.com/KamranMackey/Ellie"
repository = "https://github.com/KamranMackey/Ellie.git"
keywords = ["discord", "bot", "serenity"]
license = "MIT"
readme = "README.md"
build = "build.rs"
include = [
	"src/**/*",
    ".env.sample",
    "build.rs",
	"Cargo.toml",
	"README.md"
]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[build-dependencies]
built = { git = "https://github.com/KamranMackey/built" }

[dependencies]
built = { git = "https://github.com/KamranMackey/built" }
chrono = "0.4"
dotenv = "0.15"
failure = "0.1"
git2 = "0.11"
graphql_client = "0.8"
humantime = "2.0"
itertools = "0.8"
lastfm-rs = { git = "https://github.com/KamranMackey/lastfm-rs" }
log = "0.4"
pretty_env_logger = "0.4"
reqwest = "0.10"
percent-encoding = "2.1"
rusqlite = { git = "https://github.com/jgallagher/rusqlite", features = ["bundled"] }
rspotify = { git = "https://github.com/KamranMackey/rspotify" }
serenity = { git = "https://github.com/KamranMackey/serenity.git", branch = "kamrans-fork" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
typemap = "0.3"
