[package]
name                = "ellie"
version             = "0.7.0-alpha"
authors             = ["Kamran Mackey <kamranm1200@gmail.com>"]
description         = "A Discord bot written in Rust with Serenity."
homepage            = "https://github.com/KamranMackey/Ellie"
repository          = "https://github.com/KamranMackey/Ellie.git"
keywords            = ["discord", "bot", "serenity"]
edition             = "2018"
license             = "MIT"
readme              = "README.md"
include             = ["src/**/*", "config.sample.toml", "Cargo.toml", "README.md"]

[dependencies]
anyhow              = "1.0.36"
aspotify            = "0.6.2"
byte-unit           = "4.0.9"
chrono              = "0.4.19"
git2                = "0.13.13"
humantime           = "2.0.1"
itertools           = "0.9.0"
lastfm-rs           = "0.4.2"
reqwest             = "0.10.10"
serde               = { version = "1.0.118", features = ["derive"] }
serde_json          = "1.0.60"
tokio               = { version = "0.2.24", features = ["full"] }
toml                = "0.5.8"
tracing             = "0.1.22"
tracing-futures     = "0.2.4"
tracing-log         = "0.1.1"
tracing-subscriber  = "0.2.15"

[dependencies.lavalink-rs]
git                 = "https://gitlab.com/nitsuga5124/lavalink-rs"
branch              = "songbird"

[dependencies.serenity]
git                 = "https://github.com/serenity-rs/serenity"
branch              = "current"
default-features    = true
features            = ["collector", "unstable", "voice"]

[dependencies.songbird]
git                 = "https://github.com/serenity-rs/songbird/"
branch              = "current"
default-features    = false
features            = ["serenity-native", "gateway"]

[dependencies.sqlx]
git                 = "https://github.com/launchbadge/sqlx"
default-features    = false
features            = ["runtime-tokio-rustls", "macros", "postgres", "uuid"]
