[package]
name = "ellie"
version = "0.5.1-alpha"
authors = ["Kamran Mackey <kamranm1200@gmail.com>"]
description = "A Discord bot written in Rust with Serenity."
homepage = "https://github.com/KamranMackey/Ellie"
repository = "https://github.com/KamranMackey/Ellie.git"
keywords = ["discord", "bot", "serenity"]
edition = "2018"
license = "MIT"
readme = "README.md"
build = "build.rs"
include = [
	"src/**/*",
    ".env.sample",
    "build.rs",
	"Cargo.toml",
	"README.md"
]

[build-dependencies]
built = { git = "https://github.com/KamranMackey/built" }

[dependencies]
built = { git = "https://github.com/KamranMackey/built" }
byte-unit = "3.0"
chrono = "0.4"
dotenv = "0.15"
git2 = "0.11"
graphql_client = "0.8"
humantime = "2.0"
image = "0.23"
isolang = "1.0" 
itertools = "0.8"
kuchiki = "0.8"
lastfm-rs = { git = "https://github.com/KamranMackey/lastfm-rs" }
log = "0.4"
pretty_env_logger = "0.4"
reqwest = "0.10"
percent-encoding = "2.1"
rusqlite = { git = "https://github.com/jgallagher/rusqlite", features = ["bundled"] }
rspotify = { git = "https://github.com/KamranMackey/rspotify" }
serenity = { git = "https://github.com/KamranMackey/serenity.git", branch = "kamrans-fork", features = ["voice"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
