[package]
name = "ellie"
version = "0.5.1-alpha"
authors = ["Kamran Mackey <kamranm1200@gmail.com>"]
description = "A Discord bot written in Rust with Serenity."
homepage = "https://github.com/KamranMackey/Ellie"
repository = "https://github.com/KamranMackey/Ellie.git"
keywords = ["discord", "bot", "serenity"]
edition = "2018"
license = "MIT"
readme = "README.md"
include = [
	"src/**/*",
    "config.sample.toml",
    "build.rs",
	"Cargo.toml",
	"README.md"
]

[dependencies]
byte-unit = "3.0.3"
chrono = "0.4.10"
git2 = "0.11.0"
graphql_client = "0.8.0"
humantime = "2.0.0"
isolang = "1.0.0"
itertools = "0.8.2"
kuchiki = "0.8.0"
lastfm-rs = { git = "https://github.com/KamranMackey/lastfm-rs" }
lazy_static = "1.4.0"
log = "0.4.8"
pretty_env_logger = "0.4.0"
reqwest = "0.10.1"
percent-encoding = "2.1.0"
rusqlite = { git = "https://github.com/jgallagher/rusqlite", features = ["bundled"] }
rspotify = { git = "https://github.com/KamranMackey/rspotify" }
serenity = { git = "https://github.com/KamranMackey/serenity.git", branch = "kamrans-fork", features = ["voice"] }
serde = { version = "1.0.104", features = ["derive"] }
serde_json = "1.0.48"
toml = "0.5.6"
sysinfo = "0.11.2"
