# ------------------------------------------------------
# The configuration File for Ellie.
# 
# GitHub: https://github.com/KamranMackey/Ellie
# -------------------------------------------------------

# The token used to connect Ellie to the Discord Bot API.
token = ''

# The bot's command prefix. Anything that starts with this
# character will be interpreted as a bot command.
prefix = ''

# The bot owner's user ID. Used to detect if the user
# sending bot commands is the bot owner; useful for
# locking down certain commands to be owner-only.
owner = ''

# The Last.fm API key to use for the bot's Last.fm
# integration.
lastfm = ''

# The API key used to connect and interact with
# Google's suite of APIs.
google = ''

# The GitHub personal authentication token to use for
# the bot's integration with the GitHub API.
github = ''

# The OpenCage API key to use for connecting and
# interacting with the OpenCage API.
opencage = ''

# Variables used for accessing the Spotify API.
[spotify]
# The Spotify API client ID.
clientID = ''
# The Spotify API client secret. 
clientSecret = ''

# The API key used to interact with the Dark Sky
# API interface.
darksky = ''

# The API key used to interact with the Nexus Mods
# API interface.
nexusmods = ''

# The bot's GitHub repository.
repository = ''
