[general]
codename = "Carbon" # reminder: bump this after each major update.

[logging]
enabled = true
level = "info"

[discord]
token = ""
prefix = ""

[api]

    [api.spotify]
    client_id = ""
    client_secret = ""

    [api.misc]
    github = ""
    google = ""
    darksky = ""
    lastfm = ""
    tmdb = ""
