[bot]

    [bot.general]
    codename = "Carbon"
    prefix = ""

    [bot.database]
    url = ""

    [bot.discord]
    token = ""

    [bot.logging]
    enabled = true
    level = "info"

[api]

    [api.music]

        [api.music.spotify]
        client_id = ""
        client_secret = ""

        [api.music.lastfm]
        api_key = ""

        [api.music.lavalink]
        host = ""
        port = 1000
        password = ""

    [api.entertainment]
    tmdb = ""

    [api.social]

        [api.social.twitter]
        api_key = ""
        api_key_secret = ""
        bearer_token = ""

    [api.services]
    github = ""
    google = ""
